sudo: required
services:
  - docker

before_install:
  - docker build -t aruzin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aruzin/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-249755586775"
  bucket_path: "docker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
